### ISSUE TITLE
what is SW/HW environment on your side?

### ISSUE THREAD

**Issue by CodeDragon18** [pangsu0613/CLOCs#11]
Hi,

CLOCs_PVCas |   | code | 95.96 % | 96.76 % | 91.08 % | **0.1 s** | 1 core @ 2.5 Ghz (Python)

what is SW/HW environment when CLOCS got the performance 0.1S in kitti website.

**Comment by pangsu0613** [comment]
I guess SW/HW means software and hardware environment? I got that results on Ubuntu 16.04, python 3.6.8, CUDA 10, pytorch-1.1.0, NVIDIA 1080 Ti. The 0.1s is not accurate, for CLOCs itself, the fusion time is almost negligible (less then 10ms per frame), the most time consuming part is the 2D and 3D detector themselves.
