### ISSUE TITLE
spconv.units cannot import "non_max_suppression"

### ISSUE THREAD

**Issue by shaunkheng97** [pangsu0613/CLOCs#13]
![nms](https://user-images.githubusercontent.com/55087987/107600379-93f58980-6c5e-11eb-8f2b-1e2629cb4aa2.PNG)

Does anyone have this issue after installing spconv?

**Comment by pangsu0613** [comment]
I remembered this mistake when I set a conda environment long time ago, it could be the pytorch and cuda is not installed properly. first, you need to check the return of 'torch.cuda.is_available()', if it returns False, it means that the your pytorch and cuda has some issues, probably they are imcompatible, you need to reinstall pytorch; if it returns True, then it could be other problems.

**Comment by Anirbanbhk88** [comment]
@shaunkheng97 I am also facing this issue. How did you solve it?
