### ISSUE TITLE
Inference on Kitti dataset

### ISSUE THREAD

**Issue by shaunkheng97** [pangsu0613/CLOCs#18]
May I know how can I run the inference on CLOCs? Do I need to write my own inference code?

**Comment by pangsu0613** [comment]
Hello @shaunkheng97 , The Evaluation section in readme illustrates how to run inference using CLOCs.

**Comment by shaunkheng97** [comment]
Is there a way to visualize my inference results on test images on 2d images or 3d point cloud?

**Comment by pangsu0613** [comment]
The outputs of CLOCs are in the same format as SECOND-V1.5, so you could use the KITTI viewer under /CLOCs/second/kittiviewer, the instructions can be found in this page, https://github.com/traveller59/second.pytorch/tree/v1.5. kittiviewer could visualize the results on 3d point cloud and images. Another option is to use the MATLAB script from official kitti object development kit, this script can visualize 2D bbox and projected 3d bbox on images. The MATLAB script is original developed to visualize kitti labels (txt files), so you need to make some small changes to use it.
