### ISSUE TITLE
Steps to use Clocs with same models but a different dataset

### ISSUE THREAD

**Issue by harris-mohamed** [pangsu0613/CLOCs#19]
Hello, 

I have read through #7  but am still confused on how I should go about training Clocs. From what I have read, it sounds like I need to train the both the 2D and 3D model with my data and have it output data in KITTI format. Then, I need to train the fusion layer. I am confused on what the KITTI format is, is this the sparse tensor representation pointed out in the paper? 

Thanks for all of your help so far, you have been extremely helpful and patient.

**Comment by pangsu0613** [comment]
Hello @harris-mohamed , KITTI format means official KITTI label format, the detail of this format can be found in the readme file in kitti object detection development kit downloaded from http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d. I understand currently the CLOCs code is a bit difficult for other people to try different 2D/3D detector setups, I plan to restructure and clean the code to make it easier to use. But currently I have some paper submission deadlines... No problem, you are more than welcome to ask any questions and I am glad to help.
