### ISSUE TITLE
KITTI dataset - number of examples in testing

### ISSUE THREAD

**Issue by Jamie725** [pangsu0613/CLOCs#34]
I found from the KITTI [website](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) that there are only 7518 testing images. However, in your readme file, it states that there are 7580 testing images. I was wondering if KITTI has changed their number of testing images or it's a typo in your readme? Thanks!

**Comment by pangsu0613** [comment]
Hello @Jamie725 , yes, you are right. There are 7518 testing samples, NOT 7580, sorry for the mistake.

**Comment by Jamie725** [comment]
Thanks a lot for the clarification!
