### ISSUE TITLE
AssertionError with latest spconv version

### ISSUE THREAD

**Issue by Jamie725** [pangsu0613/CLOCs#35]
As title. This happens at spconv/spconv/utils/__init__.py. 
Current version of spconv of this file has this default setting:
===================================
def points_to_voxel( ...
                                full_mean=False,
                                block_filtering=True,
                                ...):

if full_mean:
        assert block_filtering is False

This will result in assertion error.

If I directly change block_filtering=False, there will be other issues.
Is there any suggestions for this version of spconv?
Could you please help me with this issue? Thanks!!!

**Comment by pangsu0613** [comment]
Hi @Jamie725 , you need to use the spconv with the commit that I mentioned in the readme. This is constraint by SECOND-V1.5.

**Comment by Jamie725** [comment]
Hi @pangsu0613,
Thanks for the information. I followed the following commands but failed building spconv:

git clone https://github.com/traveller59/spconv.git
cd spconv
git checkout 8da6f967fb9a054d8870c3515b1b44eca2103634

I got building errors with: 
error: no matching function for call to ‘torch::jit::RegisterOperators::RegisterOperators(const char [28], <unresolved overloaded function type>)’
   20 |     torch::jit::RegisterOperators("spconv::get_indice_pairs_2d", &spconv::getIndicePair<2>)

![image](https://user-images.githubusercontent.com/12296066/122785717-9c4f7800-d281-11eb-97f2-86e24dda571c.png)

Therefore, I was wondering if I did anything wrong. Could you please share with me the some suggested instructions to install this specific commit on spconv?

Thank you very much for your help!

**Comment by pangsu0613** [comment]
Hello @Jamie725 , I understand installing spconv is not easy. You can try change torch::jit::RegisterOperators into torch::RegisterOperators() under /spconv/src/spconv/all.cc.
You can also check the issues section in spconv repo for other instructions.

**Comment by Jamie725** [comment]
Hi @pangsu0613,
It works! Thank you very much for your help!

**Comment by Anirbanbhk88** [comment]
@Jamie725 how did you solve the above issue
