### ISSUE TITLE
Question about performance on official test Leaderboard

### ISSUE THREAD

**Issue by Viczyf** [pangsu0613/CLOCs#50]
Thanks for your sharing.
I noticed that the CLOCs achieves much better performance on the official leaderboard than the number claimed in the paper. Can you please tell me how do you optimize the method or is there some bug?
http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d
@pangsu0613

**Comment by pangsu0613** [comment]
Hello @Viczyf, CLOCs can work with any pre-trained 3D and 2D detectors, so theoratically, if you have a better 3D/2D detector, you will have better performance. The new results of CLOCs on the kitti leaderboard is achieved by fusing the CT3D and cascade-RCNN, also with couple of small modifications, we will update the repo to include more better 3D detectors.

**Comment by Viczyf** [comment]
Thank you.
