### ISSUE TITLE
Can you provide more fusion models at your paper

### ISSUE THREAD

**Issue by Joeless** [pangsu0613/CLOCs#59]
Hi~ @pangsu0613 
I like your works~
I read your paper and found that you have done a lot of model experiments, but your repo only provides Second+Cascade-RCNN
Can you provide more fusion models at your paper？

**Comment by Joeless** [comment]
Hi~
Can you provide 2D det model?   
I think the 2d det model should  add  in this repo

**Comment by pangsu0613** [comment]
Thank you for your interests in CLOCs! Replacing 2D detections is quite easy for the current codebase, you could just replace the 2D detection filtes with yours, but the files should be in KITTI format.

**Comment by Joeless** [comment]
> Thank you for your interests in CLOCs! Replacing 2D detections is quite easy for the current codebase, you could just replace the 2D detection filtes with yours, but the files should be in KITTI format.

Thank you for your answer~
2D detection result is easy to replace
I find your recently work about fast-clocs，congratulations on your interesting article , When will this code be released？

**Comment by pangsu0613** [comment]
I have started working on this, I plan to release it in April. thank you for your interests.
