### ISSUE TITLE
no model named second

### ISSUE THREAD

**Issue by Debtor141** [pangsu0613/CLOCs#74]
python create_data.py create_kitti_info_file --data_path=CLOCs/KITTI_DATASET
Traceback (most recent call last):
  File "create_data.py", line 11, in <module>
    from second.core import box_np_ops
ModuleNotFoundError: No module named 'second'

i met this error before and dont know how to slove

**Comment by shayari21** [comment]
Hello, how did you solve this error?

**Comment by Debtor141** [comment]
我之前使用3060ti和cuda11.3，出现了这个问题，查阅了一些博客之后，我租了1080ti和使用cuda9.2在autodl，问题得到解决。

**Comment by Debtor141** [comment]
> Hello, how did you solve this error?

I was using 3060ti and cuda11.3 and had this problem, after checking some blogs I rented 1080ti and used cuda9.2 in autodl and the problem was resolved.
