### ISSUE TITLE
Depth information from 2D boxes（Cascade-Rcnn）

### ISSUE THREAD

**Issue by xuV2** [pangsu0613/CLOCs#76]
Hi! @pangsu0613 . Can we get the depth information of each 2Dbox through the matrix provided by KITTI? Just like we can project a 3Dbox onto a 2Dbox.

**Comment by pangsu0613** [comment]
Hello @xuV2 , may I know what does "matrix provided by KITTI" refer to? The annotated labels provided by KITTI has the 2D and 3D bounding box, classification information.

**Comment by xuV2** [comment]
@pangsu0613  Sorry, I mean can I get 3Dbox through 2Dbox (cascade-rcnn) projection?

**Comment by pangsu0613** [comment]
I don’t think so. 2D bbox loses one dimension (depth), you can project the 2D bbox from image back to 3D, but you will get a frustum region instead of a 3D bbox.

**Comment by xuV2** [comment]
thank you for your reply
