### ISSUE TITLE
Questions about draw figures of qualitative results.

### ISSUE THREAD

**Issue by Eaphan** [pangsu0613/CLOCs#77]
When I draw the bounding boxes with mayavi, I found the line is not smooth. Do you use the mayavi too? How can you draw lines that seem quite smooth and avoid jaggies?
Thank your very much.

**Comment by pangsu0613** [comment]
Hello @Eaphan , I didn't use mayavi tool to draw the bounding boxes. You can find many other visualization tools from Github that take KITTI results format as input.
